### ISSUE TITLE
Build Failure in SparkProtocol::description when performing './make.sh clean all 

### ISSUE THREAD

**Issue by sedurCode** [pingdynasty/OpenSoundModule#4] opened 2018-04-25 16:05 UTC
Hi all,
I am still quite new to make based build systems and cross-compiling, so I will include as much details as I think I need.
I am trying to build the OpenSoundModule firmware, including the program-dfu part, but using the command: 
```bash
./make.sh clean all
```
from the ~/OpenSoundModule/firmware directory.
However, every time I include 'all', I get this error:
![image](https://user-images.githubusercontent.com/25512064/39257591-cd79ad5c-48a9-11e8-89c8-8060aa9fa757.png)
However, if I just perform:
```bash
./make.sh clean
```
I get successful compilation, but obviously without the program necessary to get my photon going.

I am using the latest versions of make, bash, Arm GCC compiler version 7-2017-major.
My operating system is up-to-date Ubutnu 16.04.4 LTS, running on a windows 10 virtual-box. 

Is this a C++ standard change problem?

Many Thanks
Simon

**Comment by pingdynasty** [comment] 2018-04-26 11:12
Hi Simon,
looks like you've found a syntax bug in the library code that would have been ignored by older versions of the compiler.
I've just tried it myself with the same compiler and can confirm the error.

**Comment by pingdynasty** [comment] 2018-04-26 11:25
So the fix to this error is to either add the compilation flag `-Wno-int-in-bool-context` or to disable `WARNINGS_AS_ERRORS` in the build script. I've pushed the latter solution.

Unfortunately there are further build errors:
```
In file included from src/stm32f2xx/concurrent_hal.cpp:34:0:
gcc-arm-none-eabi-7-2017-q4-major/arm-none-eabi/include/c++/7.2.1/mutex: In member function 'bool std::recursive_timed_mutex::_M_timedlock(const __gthread_time_t&)':
gcc-arm-none-eabi-7-2017-q4-major/arm-none-eabi/include/c++/7.2.1/mutex:292:17: error: '__gthread_recursive_mutex_timedlock' was not declared in this scope
       { return !__gthread_recursive_mutex_timedlock(&_M_mutex, &__ts); }
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc-arm-none-eabi-7-2017-q4-major/arm-none-eabi/include/c++/7.2.1/mutex:292:17: note: suggested alternative: '__gthread_recursive_mutex_trylock'
       { return !__gthread_recursive_mutex_timedlock(&_M_mutex, &__ts); }
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 __gthread_recursive_mutex_trylock
../build/module.mk:232: recipe for target '../build/target/hal/platform-6/./src/stm32f2xx/concurrent_hal.o' failed
```
The Spark library code that we use hasn't been brought up to date in a long time, the right thing to do would be to update everything to the latest version. However this will be quite complicated because we rely on a number of local changes and updates to the Spark code which will have to be manually backported. I suspect the Spark libraries have evolved quite a bit since we last did these changes.

So... to help you solve your current issues, Simon: are you making code changes or adaptations or just looking to flash the firmware on the device?
If it's the latter then there's a pre-built firmware image that you can use: https://github.com/pingdynasty/OpenSoundModule/releases
Happy to guide you through the process.

Otherwise there seem to be two options: upgrade the Spark libraries and backport local changes, or downgrade the arm-gcc compiler to a version that works with the current codebase.

**Comment by pingdynasty** [comment] 2018-04-26 12:42
Problem reported here:
https://community.particle.io/t/problems-compiling-particle-firmware/33335

**Comment by pingdynasty** [comment] 2018-04-26 12:47
okay so I can confirm it builds with `gcc-arm-none-eabi-5_4-2016q3`
available here:
https://launchpad.net/gcc-arm-embedded/+download

**Comment by sedurCode** [comment] 2018-04-27 06:45
Hi, thank you for your help.
I would be happy to have a go with a pre-built image to get started with, but I would be keen to get into making changes and adaptations. So it sounds like using an old compiler is a good way to go for now, on this project. I will have a go with the 5.4 compiler you have linked this morning, to see if I can just carry on anyway with the project in the current state.
I would love to help you update the libraries to the latest versions (everyone loves a challenge), but I don't know enough about the process, (let alone your customisations) to be of any help. I am still very new to this style of software, and this style of building software.

**Comment by sedurCode** [comment] 2018-04-27 08:34
To use that compiler to execute the build, I had to install gcc-multilib, to get around using the 32bit nature of the compiler.

**Comment by pingdynasty** [comment] 2018-04-27 09:05
Ah yes that's right, it's the last version they offered in 32-bit and for some reason it's not available in 64-bit.

**Comment by sedurCode** [comment] 2018-04-27 11:52
I have managed to complete the build, so I guess this issue is closed for the mean time?
I now have to debug dfu-util, but at least I am close :)

![image](https://user-images.githubusercontent.com/25512064/39361309-d02275e0-4a19-11e8-949f-e862093933ac.png)

**Comment by sedurCode** [comment] 2018-04-27 11:55
scrap that, just had to perform as sudo.

**Comment by pingdynasty** [comment] 2018-04-27 12:05
great :+1: 
I'll close this now even though there are some relevant new questions raised.
Feel free to raise more issues if you start hacking the code!

**Closed as completed by pingdynasty** 2018-04-27 12:05 UTC
